/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upac;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import upac.helper.Agenda;
import upac.helper.DatabaseManager;
import upac.helper.Login;
import upac.helper.UniversalMethod;

/**
 *
 * @author user
 */
public class MemberDetail extends javax.swing.JDialog {

    /**
     * Creates new form MemberDetail
     */
    public static int rowId;
    private DatabaseManager db;
    public MemberDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db = Login.db;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        setDefaultImage(UniversalMethod.convertStringToImageIcon( UniversalMethod.data.get(rowId).getProfile()), profile);
        setDefaultImage(UniversalMethod.convertStringToImageIcon( UniversalMethod.data.get(rowId).getMatricule()), matricule);
        UniversalMethod.addChartToPanel(statistic);
        
        
        fullname.setText( UniversalMethod.data.get(rowId).getNom());
        poste.setText(UniversalMethod.data.get(rowId).getPoste());
        affectation.setText(affectation.getText() +" : "+ UniversalMethod.data.get(rowId).getAffectation());
        bureau.setText(bureau.getText() +" : "+ UniversalMethod.data.get(rowId).getBureau());
        division.setText(division.getText() +" : "+ UniversalMethod.data.get(rowId).getDivision());
        email.setText(email.getText() +" : "+ UniversalMethod.data.get(rowId).getEmail());
        contact.setText(contact.getText() +" : "+ UniversalMethod.data.get(rowId).getPhone());
        instutition.setText(instutition.getText() +" : "+ UniversalMethod.data.get(rowId).getInstitution());
        
        if (db.checkActivation(UniversalMethod.data.get(rowId).getId())) {
            active.setVisible(false);
        }
        else{
            desactive.setVisible(false);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        poste = new javax.swing.JLabel();
        matricule = new javax.swing.JLabel();
        instutition = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        affectation = new javax.swing.JLabel();
        division = new javax.swing.JLabel();
        bureau = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        active = new javax.swing.JButton();
        desactive = new javax.swing.JButton();
        statistic = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 56, 91)));
        jPanel1.setMaximumSize(new java.awt.Dimension(590, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 22, 106, 106));

        fullname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 382, 37));

        poste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(poste, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 286, 24));

        matricule.setText("jLabel3");
        jPanel1.add(matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 120, 100));

        instutition.setBackground(new java.awt.Color(77, 56, 91));
        instutition.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        instutition.setText("Institution ");
        jPanel1.add(instutition, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 169, 279, 27));

        contact.setBackground(new java.awt.Color(77, 56, 91));
        contact.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        contact.setText("Contact");
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 290, 279, 27));

        affectation.setBackground(new java.awt.Color(77, 56, 91));
        affectation.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        affectation.setText("Affectation");
        jPanel1.add(affectation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 279, 27));

        division.setBackground(new java.awt.Color(77, 56, 91));
        division.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        division.setText("Division");
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 207, 279, 27));

        bureau.setBackground(new java.awt.Color(77, 56, 91));
        bureau.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        bureau.setText("Bureau");
        jPanel1.add(bureau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 279, 27));

        email.setBackground(new java.awt.Color(77, 56, 91));
        email.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        email.setText("Email");
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 279, 27));

        active.setBackground(new java.awt.Color(77, 56, 91));
        active.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        active.setForeground(new java.awt.Color(255, 255, 255));
        active.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Unlock.png"))); // NOI18N
        active.setText("Activer");
        active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeActionPerformed(evt);
            }
        });
        jPanel1.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 160, 50));

        desactive.setBackground(new java.awt.Color(204, 0, 0));
        desactive.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        desactive.setForeground(new java.awt.Color(255, 255, 255));
        desactive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Lock.png"))); // NOI18N
        desactive.setText("Desactiver");
        desactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desactiveActionPerformed(evt);
            }
        });
        jPanel1.add(desactive, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 170, 50));

        javax.swing.GroupLayout statisticLayout = new javax.swing.GroupLayout(statistic);
        statistic.setLayout(statisticLayout);
        statisticLayout.setHorizontalGroup(
            statisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        statisticLayout.setVerticalGroup(
            statisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jPanel1.add(statistic, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 240, 220));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeActionPerformed
        // TODO add your handling code here:
        active.setIcon(new ImageIcon(getClass().getResource("/images/ajax_loader_gray_32.gif")));
        int bureau = db.getBureauId(
                UniversalMethod.data.get(rowId).getBureau());
        db.activateMembers(
                UniversalMethod.data.get(rowId).getId(),
                bureau,
                UniversalMethod.data.get(rowId).getEmail(), 
                UniversalMethod.data.get(rowId).getPassword(), 
                UniversalMethod.getCurrentDateAndTime(), 
                1);
        if ( !db.getCarteById(UniversalMethod.data.get(rowId).getId()) ) {
            this.dispose();
            CarteDialog.rowId = rowId;
            CarteDialog carte = new CarteDialog(new javax.swing.JFrame(), true);
            carte.setVisible(true);
        }
        else{            
            this.dispose();
        }
        
    }//GEN-LAST:event_activeActionPerformed

    private void desactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desactiveActionPerformed
        // TODO add your handling code here:
        desactive.setIcon(new ImageIcon(getClass().getResource("/images/ajax_loader_gray_32.gif")));
        db.deleteActivation(UniversalMethod.data.get(rowId).getId());
        this.dispose();
    }//GEN-LAST:event_desactiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MemberDetail dialog = new MemberDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void setDefaultImage(ImageIcon imageIcon, JLabel label){
       
        Image image = imageIcon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            
        ImageIcon iconResized = new ImageIcon(image);
            
        label.setIcon(iconResized);
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton active;
    private javax.swing.JLabel affectation;
    private javax.swing.JLabel bureau;
    private javax.swing.JLabel contact;
    private javax.swing.JButton desactive;
    private javax.swing.JLabel division;
    private javax.swing.JLabel email;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel instutition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matricule;
    private javax.swing.JLabel poste;
    private javax.swing.JLabel profile;
    private javax.swing.JPanel statistic;
    // End of variables declaration//GEN-END:variables
}
