/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upac;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static upac.StudentDetailDivers.apparitora;
import static upac.StudentDetailDivers.rowId;
import upac.helper.Agenda;
import upac.helper.DatabaseManager;
import upac.helper.Login;
import upac.helper.UniversalMethod;
import upac.universalclasses.FraisMaladieStudent;

/**
 *
 * @author user
 */
public class StudentDetailMaladie extends javax.swing.JDialog {

    /**
     * Creates new form MemberDetail
     */
    public static int rowId;
    public static boolean apparitora = false;
    private DatabaseManager db;
    public static String promotion;
    ArrayList<FraisMaladieStudent> student;
    
    public StudentDetailMaladie(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db = Login.db;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        student = UniversalMethod.fraisMaladie;
        if (student != null) {
            
            setDefaultImage(UniversalMethod.convertStringToImageIcon( student.get(rowId).getProfile()), profile);
            setDefaultImage(UniversalMethod.convertStringToImageIcon( student.get(rowId).getMatricule()), matricule);
            setDefaultImage(UniversalMethod.convertStringToImageIcon( student.get(rowId).getBordereau()), bordereau);

            fullname.setText(student.get(rowId).getFullname());
            faculte.setText(student.get(rowId).getFaculte());

            if (apparitora) {
                active.setVisible(true);
            }
            else{
                active.setVisible(false);

            }
            
        }
//       
//        if (db.checkActivation(UniversalMethod.data.get(rowId).getId())) {
//            active.setVisible(false);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        matricule = new javax.swing.JLabel();
        fullname = new javax.swing.JLabel();
        faculte = new javax.swing.JLabel();
        active = new javax.swing.JButton();
        bordereau = new javax.swing.JLabel();
        profile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(77, 56, 91)));
        jPanel1.setMaximumSize(new java.awt.Dimension(590, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        matricule.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(matricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 106, 106));

        fullname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        fullname.setText("Billy Paul");
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 360, 37));

        faculte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        faculte.setText("Faculté de Science");
        jPanel1.add(faculte, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 286, 24));

        active.setBackground(new java.awt.Color(77, 56, 91));
        active.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        active.setForeground(new java.awt.Color(255, 255, 255));
        active.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Unlock.png"))); // NOI18N
        active.setText("Activer");
        active.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activeActionPerformed(evt);
            }
        });
        jPanel1.add(active, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 160, 50));

        bordereau.setText("jLabel1");
        jPanel1.add(bordereau, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 320, 220));

        profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 106, 106));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void activeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activeActionPerformed
        // TODO add your handling code here:
        active.setIcon(new ImageIcon(getClass().getResource("/images/ajax_loader_gray_32.gif")));
        db.confirmationStatusPayementMadelie(
                student.get(rowId).getFraisId(),
                student.get(rowId).getStudentId(),
                student.get(rowId).getNumeroBordereau(),
                student.get(rowId).getBordereau(),
                student.get(rowId).getPromotion(),
                UniversalMethod.getCurrentDateAndTime()
        );
        this.dispose();
        JOptionPane.showMessageDialog(null, "Payement Confirmé "+ student.get(rowId).getFullname());
        
    }//GEN-LAST:event_activeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetailMaladie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetailMaladie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetailMaladie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetailMaladie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentDetailMaladie dialog = new StudentDetailMaladie(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void setDefaultImage(ImageIcon imageIcon, JLabel label){
       
        Image image = imageIcon.getImage().getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            
        ImageIcon iconResized = new ImageIcon(image);
            
        label.setIcon(iconResized);
        
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton active;
    private javax.swing.JLabel bordereau;
    private javax.swing.JLabel faculte;
    private javax.swing.JLabel fullname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matricule;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
