/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upac.helper;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author user
 */
public class AjouteEtudiant extends javax.swing.JDialog {

    /**
     * Creates new form AjoutMembre
     */
    SpinnerListModel model;
    DatabaseManager db;
    File file;
    String[] affectationSpinner = {"Apparitora", "Inscription", "Assurance Maladie", "Frais Divers", "Frais Academique"};
    String[] posteSpinner = {"Appariteur", "Administrateur Chef Technique", "Chef de bureaux"};
    //JSpinner affectation ;
    public AjouteEtudiant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        addItemToSpinner();
        db = Login.db;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        setDefaultImageLogo(new ImageIcon(getClass().getResource("/images/upac-logo-300x298.png")));
        setDefaultImage(new ImageIcon(getClass().getResource("/images/People.png")), respo);
        
        setDefaultImage(new ImageIcon(getClass().getResource("/images/Male.png")), etud);
        setDefaultImage(new ImageIcon(getClass().getResource("/images/avatar2.jpeg")), profile);
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
        
        //Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png"));
        //new ImageIcon(getClass().getResource("/images/upac-logo-300x298.png")).getImage());
        //this.setIconImage(new ImageIcon(getClass().getResource("/images/upac-logo-300x298.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        postnom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        nomResponsable = new javax.swing.JTextField();
        createStudent = new javax.swing.JButton();
        imagePorfile = new javax.swing.JButton();
        profile = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        professionResponsable = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        contactResponsable = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        faculte = new javax.swing.JComboBox<>();
        departement = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        genre = new javax.swing.JRadioButton();
        genre1 = new javax.swing.JRadioButton();
        promotion = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        postNomResponsable = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addressResponsable = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        respo = new javax.swing.JLabel();
        etud = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(813, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 56, 91));
        jLabel1.setText("Information du Responsable");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 460, 40));

        jLabel2.setBackground(new java.awt.Color(77, 56, 91));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Post Nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jLabel3.setBackground(new java.awt.Color(77, 56, 91));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Genre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 20));

        jLabel4.setBackground(new java.awt.Color(77, 56, 91));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 80, 20));

        jLabel5.setBackground(new java.awt.Color(77, 56, 91));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pre Nom");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        jLabel6.setBackground(new java.awt.Color(77, 56, 91));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nom");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 90, 20));

        jLabel7.setBackground(new java.awt.Color(77, 56, 91));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nom");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 20));

        nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 30));

        postnom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        postnom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(postnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 30));

        prenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        prenom.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 148, 180, 30));

        address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        address.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, 30));

        contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contact.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 240, 30));

        nomResponsable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomResponsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(nomResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 180, 30));

        createStudent.setBackground(new java.awt.Color(77, 56, 91));
        createStudent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createStudent.setForeground(new java.awt.Color(255, 255, 255));
        createStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Apply.png"))); // NOI18N
        createStudent.setText("Create");
        createStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentActionPerformed(evt);
            }
        });
        jPanel1.add(createStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 190, 50));

        imagePorfile.setBackground(new java.awt.Color(77, 56, 91));
        imagePorfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imagePorfile.setForeground(new java.awt.Color(255, 255, 255));
        imagePorfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        imagePorfile.setText("Photo Etud");
        imagePorfile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        imagePorfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePorfileActionPerformed(evt);
            }
        });
        jPanel1.add(imagePorfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, 38));

        profile.setBackground(new java.awt.Color(0, 51, 102));
        profile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 2, true));
        profile.setOpaque(true);
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 150, 160));

        jLabel8.setBackground(new java.awt.Color(77, 56, 91));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Profession");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 80, 20));

        professionResponsable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        professionResponsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        professionResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professionResponsableActionPerformed(evt);
            }
        });
        jPanel1.add(professionResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 180, 30));

        jLabel9.setBackground(new java.awt.Color(77, 56, 91));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contact");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 80, 20));

        contactResponsable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        contactResponsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        jPanel1.add(contactResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 180, 30));

        jLabel10.setBackground(new java.awt.Color(77, 56, 91));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Faculte");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 50, -1));

        jLabel11.setBackground(new java.awt.Color(77, 56, 91));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Departement");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, -1, -1));

        jLabel12.setBackground(new java.awt.Color(77, 56, 91));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Promotion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 80, 20));

        faculte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        faculte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculte des sciences et techniques", "Faculte des sciences humaines" }));
        faculte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
        faculte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faculteActionPerformed(evt);
            }
        });
        jPanel1.add(faculte, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 240, 30));

        departement.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departement.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] {
                "Département de Génie Civil/Architecture",
                "épartement de Génie Informatique",
                "Département des Sciences de Santé",
                "Département de Droit",
                "Département de l’Economie",
                "Département des sciences de l’Information et de la Communication"
            }));
            departement.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
            jPanel1.add(departement, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 240, 30));

            jLabel13.setBackground(new java.awt.Color(77, 56, 91));
            jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel13.setText("Address");
            jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 20));

            genre.setBackground(new java.awt.Color(255, 255, 255));
            genre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            genre.setForeground(new java.awt.Color(77, 56, 91));
            genre.setText("Homme");
            jPanel1.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

            genre1.setBackground(new java.awt.Color(255, 255, 255));
            genre1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            genre1.setForeground(new java.awt.Color(77, 56, 91));
            genre1.setText("Femme");
            jPanel1.add(genre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

            promotion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAC 1", "BAC 2", "BAC 3" }));
            promotion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
            jPanel1.add(promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 240, 30));

            jSeparator1.setForeground(new java.awt.Color(77, 56, 91));
            jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 298, 780, -1));

            jLabel14.setBackground(new java.awt.Color(77, 56, 91));
            jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel14.setText("Post Nom");
            jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 20));

            postNomResponsable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            postNomResponsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
            postNomResponsable.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    postNomResponsableActionPerformed(evt);
                }
            });
            jPanel1.add(postNomResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 180, 30));

            jLabel15.setBackground(new java.awt.Color(77, 56, 91));
            jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jLabel15.setText("Address");
            jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 80, 20));

            addressResponsable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            addressResponsable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(77, 56, 91), 1, true));
            addressResponsable.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addressResponsableActionPerformed(evt);
                }
            });
            jPanel1.add(addressResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 180, 30));

            jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
            jLabel16.setForeground(new java.awt.Color(77, 56, 91));
            jLabel16.setText("Information d'etudiant");
            jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 310, 40));
            jPanel1.add(respo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 30, 30));
            jPanel1.add(etud, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));
            jPanel1.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void professionResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professionResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professionResponsableActionPerformed

    private void faculteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faculteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_faculteActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void postNomResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postNomResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postNomResponsableActionPerformed

    private void addressResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressResponsableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressResponsableActionPerformed

    private void imagePorfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePorfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int imageChooser = fileChooser.showOpenDialog(null);
        fileChooser.setDialogTitle("Selectioner le photo...");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        if ( imageChooser == JFileChooser.APPROVE_OPTION ) {
            file = fileChooser.getSelectedFile();
            String profileName = file.getName();
            String profilePath = file.getAbsolutePath();
            imagePorfile.setText(profileName);
            
            ImageIcon icon = new ImageIcon(profilePath);
            Image image = icon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon iconResized = new ImageIcon(image);
            
            profile.setIcon(iconResized);
        }
    }//GEN-LAST:event_imagePorfileActionPerformed

    private void createStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentActionPerformed
        // TODO add your handling code here:
        
        if ( !nom.getText().equals("") && !postnom.getText().equals("") && !prenom.getText().equals("")
                && !genre.getText().equals(" ") && !contact.getText().equals(" ") && !promotion.getSelectedItem().toString().equals("")
                && !faculte.getSelectedItem().toString().equals("") && !departement.getSelectedItem().toString().equals("")
                && !nomResponsable.getText().equals("") && !postNomResponsable.getText().equals("")
                && !addressResponsable.getText().equals("") && !professionResponsable.getText().equals("") && ! contactResponsable.getText().equals("")) {
            if (file != null) {
                createStudent.setIcon(new ImageIcon(getClass().getResource("/images/ajax_loader_gray_32.gif")));
                db.addStudent(nom.getText(), postnom.getText(), prenom.getText(), genre.getText(),
                    address.getText(), contact.getText() ,promotion.getSelectedItem().toString(),
                    faculte.getSelectedItem().toString(), departement.getSelectedItem().toString(),
                    UniversalMethod.encodeFileToBase64Binary(file), "matricule", 
                    0, UniversalMethod.getCurrentDateAndTime(), nomResponsable.getText(),
                    postNomResponsable.getText(), addressResponsable.getText(), 
                    professionResponsable.getText(), contactResponsable.getText());
                InscBordereau.idStudent = db.getStudentByNames(nom.getText(), postnom.getText(), prenom.getText(), promotion.getSelectedItem().toString());
                this.dispose();
                //JOptionPane.showMessageDialog(null, UniversalMethod.encodeFileToBase64Binary(file));
                new InscBordereau(null, true).setVisible(true);
                
        
            }
            else{
                JOptionPane.showMessageDialog(null, "Veuillez selectionner le photo de l'etudiant et ressayer!!!");
            }
        }
        else{
             JOptionPane.showMessageDialog(null, "Veuillez remplir toute les formulaire!!!");
        }
        
    }//GEN-LAST:event_createStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouteEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouteEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouteEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouteEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AjouteEtudiant dialog = new AjouteEtudiant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void addItemToSpinner(){
        //model = new SpinnerListModel(affectationSpinner);
//        affectation.addItem(affectationSpinner[0]);
//        affectation.addItem(affectationSpinner[1]);
//        affectation.addItem(affectationSpinner[2]);
//        affectation.addItem(affectationSpinner[3]);
//        affectation.addItem(affectationSpinner[4]);
//        
//        poste.addItem(posteSpinner[0]);
//        poste.addItem(posteSpinner[1]);
//        poste.addItem(posteSpinner[2]);
        //affectation = new JSpinner(model);
        //jSpinnerPanell.add(affectation);
    }
    private void setDefaultImageLogo(ImageIcon imageIcon){
       
        Image image = imageIcon.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_SMOOTH);
            
        ImageIcon iconResized = new ImageIcon(image);
            
        logo.setIcon(iconResized);
        
    }
    private void setDefaultImage(ImageIcon imageIcon, JLabel lable){
       
        Image image = imageIcon.getImage().getScaledInstance(lable.getWidth(), lable.getHeight(), Image.SCALE_SMOOTH);
            
        ImageIcon iconResized = new ImageIcon(image);
            
        lable.setIcon(iconResized);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField addressResponsable;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField contactResponsable;
    private javax.swing.JButton createStudent;
    private javax.swing.JComboBox<String> departement;
    private javax.swing.JLabel etud;
    private javax.swing.JComboBox<String> faculte;
    private javax.swing.JRadioButton genre;
    private javax.swing.JRadioButton genre1;
    private javax.swing.JButton imagePorfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField nomResponsable;
    private javax.swing.JTextField postNomResponsable;
    private javax.swing.JTextField postnom;
    private javax.swing.JTextField prenom;
    private javax.swing.JTextField professionResponsable;
    private javax.swing.JLabel profile;
    private javax.swing.JComboBox<String> promotion;
    private javax.swing.JLabel respo;
    // End of variables declaration//GEN-END:variables
}
