/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package upac.helper;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JSpinner;
import javax.swing.SpinnerListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import upac.ServiceTechnique;

/**
 *
 * @author user
 */
public class UpdateMembre extends javax.swing.JDialog {

    /**
     * Creates new form AjoutMembre
     */
    SpinnerListModel model;
    String[] affectationSpinner = {"Apparitora", "Inscription", "Assurance Maladie", "Frais Divers", "Frais Academique"};
    String[] posteSpinner = {"Appariteur", "Administrateur Chef Technique", "Chef de bureaux"};
    //JSpinner affectation ;
    File file = null;
    private DatabaseManager db;
    public UpdateMembre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        addItemToSpinner();
        setData();
        setDefaultImage(new ImageIcon(getClass().getResource("/images/default.jpg")));
        db = Login.db;
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/upac-logo-300x298.png")));
    }
    //ptrckbyamasu@gmail.com

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        postnom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        instutition = new javax.swing.JTextField();
        create = new javax.swing.JButton();
        imagePorfile = new javax.swing.JButton();
        profile = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        division = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        affectation = new javax.swing.JComboBox<>();
        poste = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        bureau = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(77, 56, 91));
        jLabel1.setText("Noveau Membre du Staff");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 20));

        jLabel2.setBackground(new java.awt.Color(77, 56, 91));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Post Nom");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 80, 20));

        jLabel4.setBackground(new java.awt.Color(77, 56, 91));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Contact");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 20));

        jLabel5.setBackground(new java.awt.Color(77, 56, 91));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Pre Nom");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, 20));

        jLabel6.setBackground(new java.awt.Color(77, 56, 91));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Instutition");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 90, 20));

        jLabel7.setBackground(new java.awt.Color(77, 56, 91));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nom");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 20));

        nom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        jPanel1.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, 30));

        postnom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(postnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 180, 30));

        prenom.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 148, 180, 30));

        contact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 30));

        instutition.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(instutition, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 180, 30));

        create.setBackground(new java.awt.Color(77, 56, 91));
        create.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Yes.png"))); // NOI18N
        create.setText("Enregistrer");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        jPanel1.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 380, 160, 41));

        imagePorfile.setBackground(new java.awt.Color(77, 56, 91));
        imagePorfile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        imagePorfile.setForeground(new java.awt.Color(255, 255, 255));
        imagePorfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Upload.png"))); // NOI18N
        imagePorfile.setText("Profile Pic");
        imagePorfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagePorfileActionPerformed(evt);
            }
        });
        jPanel1.add(imagePorfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, 38));

        profile.setBackground(new java.awt.Color(0, 51, 102));
        profile.setOpaque(true);
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 170));

        jLabel8.setBackground(new java.awt.Color(77, 56, 91));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Division");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 80, 20));

        division.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel1.add(division, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 180, 30));

        jLabel9.setBackground(new java.awt.Color(77, 56, 91));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Bureau");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, 20));

        jLabel10.setBackground(new java.awt.Color(77, 56, 91));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Affectation");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 80, -1));

        jLabel11.setBackground(new java.awt.Color(77, 56, 91));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Poste");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 70, -1));

        jLabel12.setBackground(new java.awt.Color(77, 56, 91));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Mot de Passe");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 150, 20));

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.setText("jPasswordField1");
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 250, 30));

        affectation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        affectation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apparitora", "Inscription", "Assurance Maladie", "Frais Divers", "Frais Academique" }));
        affectation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affectationActionPerformed(evt);
            }
        });
        jPanel1.add(affectation, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 170, 30));

        poste.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        poste.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Appariteur", "Administrateur Chef Technique", "Chef de bureaux" }));
        jPanel1.add(poste, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 170, 30));

        jLabel13.setBackground(new java.awt.Color(77, 56, 91));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Email");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 150, 20));

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 250, 30));

        bureau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Administrateur Principale",
            "Administrateur Adjoint",
            "Bureau A",
            "Bureau B",
            "Bureau C",
            "Bureau D"}));
jPanel1.add(bureau, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 180, 30));

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divisionActionPerformed

    private void affectationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affectationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affectationActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void imagePorfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagePorfileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int imageChooser = fileChooser.showOpenDialog(null);
        fileChooser.setDialogTitle("Selectioner le photo...");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        fileChooser.setFileFilter(filter);
        if ( imageChooser == JFileChooser.APPROVE_OPTION ) {
            file = fileChooser.getSelectedFile();
            String profileName = file.getName();
            String profilePath = file.getAbsolutePath();
            imagePorfile.setText(profileName);
            
            ImageIcon icon = new ImageIcon(profilePath);
            Image image = icon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
            
            ImageIcon iconResized = new ImageIcon(image);
            
            profile.setIcon(iconResized);
        }
    }//GEN-LAST:event_imagePorfileActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        /*updateMembre(String first_name, String second_name, String last_name, 
            String instutition, String division, String matricule,
            String contact, String email, String bureau, String affectation, 
            String poste, String password, String timestamp, int id, String profile)*/
        if ( !nom.getText().equals("") && !postnom.getText().equals("") && !prenom.getText().equals("") && !instutition.getText().equals("") 
            && !division.getText().equals("") && !contact.getText().equals("") && !email.getText().equals("") && !bureau.getSelectedItem().toString().equals("") 
            && !affectation.getSelectedItem().toString().equals("") && !poste.getSelectedItem().toString().equals("") && !password.getText().equals("")
            && password.getText().length() > 4 ) {
            String date = UniversalMethod.getCurrentDateAndTime();
            System.out.println("Current date is : "+ date);
            if (file != null) {
                db.updateMembre(
                        nom.getText().trim(), 
                        postnom.getText().trim(), 
                        prenom.getText().trim(), 
                        instutition.getText().trim(), 
                        division.getText().trim(),
                        "matricule",
                        contact.getText().trim(), 
                        email.getText().trim(), 
                        bureau.getSelectedItem().toString(), 
                        affectation.getSelectedItem().toString(), 
                        poste.getSelectedItem().toString(), 
                        password.getText().trim(), 
                        date, 
                        UniversalMethod.admindata.getId(), 
                        UniversalMethod.encodeFileToBase64Binary(file));
                    db. updateAdminState(email.getText().trim(), password.getText().trim(), 1, UniversalMethod.admindata.getId());
                    this.setVisible(false);
                    ServiceTechnique technique = new ServiceTechnique();
                    technique.setVisible(true);       
            }
            else{
               db.updateMembre(
                        nom.getText().trim(), 
                        postnom.getText().trim(), 
                        prenom.getText().trim(), 
                        instutition.getText().trim(), 
                        division.getText().trim(),
                        "matricule",
                        contact.getText().trim(), 
                        email.getText().trim(), 
                        bureau.getSelectedItem().toString(), 
                        affectation.getSelectedItem().toString(), 
                        poste.getSelectedItem().toString(), 
                        password.getText().trim(), 
                        date, 
                        UniversalMethod.admindata.getId(), 
                        null);
                    db. updateAdminState(email.getText().trim(), password.getText().trim(), 1, UniversalMethod.admindata.getId());
                    this.setVisible(false);
                    ServiceTechnique technique = new ServiceTechnique();
                    technique.setVisible(true);       
            }
           
        }
    }//GEN-LAST:event_createActionPerformed

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        password.setText("");
    }//GEN-LAST:event_passwordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateMembre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateMembre dialog = new UpdateMembre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void setData(){
        String[] fullname = UniversalMethod.admindata.getNom().split(" ");
        instutition.setText(UniversalMethod.admindata.getInstitution());
        division.setText(UniversalMethod.admindata.getDivision());
        contact.setText(UniversalMethod.admindata.getPhone());
        email.setText(UniversalMethod.admindata.getEmail());
        nom.setText(fullname[0]);
        postnom.setText(fullname[1]);
        prenom.setText(fullname[2]);
        
    }
    private void addItemToSpinner(){
        //model = new SpinnerListModel(affectationSpinner);
//        affectation.addItem(affectationSpinner[0]);
//        affectation.addItem(affectationSpinner[1]);
//        affectation.addItem(affectationSpinner[2]);
//        affectation.addItem(affectationSpinner[3]);
//        affectation.addItem(affectationSpinner[4]);
//        
//        poste.addItem(posteSpinner[0]);
//        poste.addItem(posteSpinner[1]);
//        poste.addItem(posteSpinner[2]);
        //affectation = new JSpinner(model);
        //jSpinnerPanell.add(affectation);
    }
    private void setDefaultImage(ImageIcon imageIcon){
       
        Image image = imageIcon.getImage().getScaledInstance(profile.getWidth(), profile.getHeight(), Image.SCALE_SMOOTH);
            
        ImageIcon iconResized = new ImageIcon(image);
            
        profile.setIcon(iconResized);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> affectation;
    private javax.swing.JComboBox<String> bureau;
    private javax.swing.JTextField contact;
    private javax.swing.JButton create;
    private javax.swing.JTextField division;
    private javax.swing.JTextField email;
    private javax.swing.JButton imagePorfile;
    private javax.swing.JTextField instutition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nom;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> poste;
    private javax.swing.JTextField postnom;
    private javax.swing.JTextField prenom;
    private javax.swing.JLabel profile;
    // End of variables declaration//GEN-END:variables
}
